apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::625173307183:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::625173307183:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1WA9TYXPF28J0
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-13T13:41:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1201"
  uid: 8b182486-cbce-40c5-97d9-aa8f23faf65f
